config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "users/sign_out", to: "users#logy"
  get 'add_item/:coc_id', to: "roads#add_item", as: 'add_item'
  get 'add_item_last/:coc_id', to: "roads#add_item_last", as: 'add_item_last'
  get 'eliminate_tray/:i_id', to: "roads#eliminate_item", as: 'eliminate_item'
  get 'pay/:order_id', to: "orders#pay", as: 'pay'
  get 'wait/:order_id', to: "orders#wait", as: 'wait'
  get 'admin', to: "orders#admin", as: 'admin'
  get 'search', to: "orders#pannel"
  get 'ready/:id', to: "orders#ready", as: 'ready'
  get 'disp/:id', to: "orders#disp", as: 'disp'
  get 'elim/:id', to: "orders#elim", as: 'elim'
  get 'elim2/:id', to:"orders#elim2", as: 'elim2'
  get 'pending', to: "orders#pending", as: 'pending'
  resources :users
  resources :customers do
    resources :orders
  end
  resources :trees do
    resources :roads
  end
  resources :trees
end

#sample@sample.com123456

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookie.rb
class Cookie < ApplicationRecord
    has_one_attached :image
    has_one :flayer
    has_one :photo
    
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders, :dependent => :delete_all
    
end

app/models/flayer.rb
class Flayer < ApplicationRecord
  belongs_to :cooky
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :roads
  

end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :cookie
  has_one_attached :picture
end

app/models/road.rb
class Road < ApplicationRecord
  belongs_to :tree
  belongs_to :order
end

app/models/tray.rb
class Tray < ApplicationRecord
  belongs_to :order
  belongs_to :tree
end

app/models/tree.rb
class Tree < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      if(cookies[:customer_idd].present?)
        puts("ya estabaaaaaaaaa")
        puts(cookies[:customer_idd].to_s)
        begin
          Order.where(id:cookies[:current_order_idd]).first.id
        rescue => exception
          e = Order.new
          e.customer = Customer.where(id:cookies[:customer_idd]).first
          e.finished = false
          e.save!
          cookies[:current_order_idd] = e.id
          puts("tenia un carro pero estaba listo")
        end
        if(!(Order.where(id:cookies[:current_order_idd]).first.finished))
          puts(cookies[:current_order_idd].to_s)
        else
          e = Order.new
          e.customer = Customer.where(id:cookies[:customer_idd]).first
          e.finished = false
          e.save!
          cookies[:current_order_idd] = e.id
          puts("tenia un carro pero estaba listo")
        end
      else
        o = Customer.new
        o.save!
        cookies[:customer_idd] = o.id
        e = Order.new
        e.customer = o
        e.finished = false
        e.save!
        cookies[:current_order_idd] = e.id
        puts("user being saved")
      end
      puts("proccess finished")
      
    end
  end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]

  # GET /trees
  # GET /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to trees_url, notice: 'Tree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tree_params
      params.fetch(:tree, {}).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roads_helper.rb
module RoadsHelper
end

app/helpers/trays_helper.rb
module TraysHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/trees/_form.html.erb
<%= form_with(model: tree, local: true) do |form| %>
<div style="margin-left:340px">
<ul class="list-group">
<li class="list-group-item">
<%= form.label :name%>
<%= form.text_field :name%></li>
<li class="list-group-item">

<%= form.label :price%>
<%= form.text_field :price%></li>
<li class="list-group-item">

  <% if tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>
      <ul>
        <% tree.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trees</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= link_to 'Show', tree %></td>
        <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
        <td><%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree', new_tree_path %>

app/views/trees/new.html.erb
<h1>New Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tree_path(@tree) %> |
<%= link_to 'Back', trees_path %>