config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "users/sign_out", to: "users#logy"
  get 'add_item/:coc_id', to: "roads#add_item", as: 'add_item'
  get 'add_item_last/:coc_id', to: "roads#add_item_last", as: 'add_item_last'
  get 'eliminate_tray/:i_id', to: "roads#eliminate_item", as: 'eliminate_item'
  get 'pay/:order_id', to: "orders#pay", as: 'pay'
  get 'wait/:order_id', to: "orders#wait", as: 'wait'
  get 'admin', to: "orders#admin", as: 'admin'
  get 'search', to: "orders#pannel"
  get 'ready/:id', to: "orders#ready", as: 'ready'
  get 'disp/:id', to: "orders#disp", as: 'disp'
  get 'elim/:id', to: "orders#elim", as: 'elim'
  get 'elim2/:id', to:"orders#elim2", as: 'elim2'
  get 'pending', to: "orders#pending", as: 'pending'
  resources :users
  resources :customers do
    resources :orders
  end
  resources :trees do
    resources :roads
  end
  resources :trees
end

#sample@sample.com123456

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookie.rb
class Cookie < ApplicationRecord
    has_one_attached :image
    has_one :flayer
    has_one :photo
    
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders, :dependent => :delete_all
    
end

app/models/flayer.rb
class Flayer < ApplicationRecord
  belongs_to :cooky
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :roads
  

end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :cookie
  has_one_attached :picture
end

app/models/road.rb
class Road < ApplicationRecord
  belongs_to :tree
  belongs_to :order
end

app/models/tray.rb
class Tray < ApplicationRecord
  belongs_to :order
  belongs_to :tree
end

app/models/tree.rb
class Tree < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    @order = Order.where(id:cookies[:current_order_idd]).first
    @order_id = @order.id
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to pay_path(@order_id), notice: 'Datos Actualizados con exito!' }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.fetch(:customer, {}).permit(:name,:last_name,:phone,:adress,:ident,:comuna)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      if(cookies[:customer_idd].present?)
        puts("ya estabaaaaaaaaa")
        puts(cookies[:customer_idd].to_s)
        begin
          Order.where(id:cookies[:current_order_idd]).first.id
        rescue => exception
          e = Order.new
          e.customer = Customer.where(id:cookies[:customer_idd]).first
          e.finished = false
          e.save!
          cookies[:current_order_idd] = e.id
          puts("tenia un carro pero estaba listo")
        end
        if(!(Order.where(id:cookies[:current_order_idd]).first.finished))
          puts(cookies[:current_order_idd].to_s)
        else
          e = Order.new
          e.customer = Customer.where(id:cookies[:customer_idd]).first
          e.finished = false
          e.save!
          cookies[:current_order_idd] = e.id
          puts("tenia un carro pero estaba listo")
        end
      else
        o = Customer.new
        o.save!
        cookies[:customer_idd] = o.id
        e = Order.new
        e.customer = o
        e.finished = false
        e.save!
        cookies[:current_order_idd] = e.id
        puts("user being saved")
      end
      puts("proccess finished")
      
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roads_helper.rb
module RoadsHelper
end

app/helpers/trays_helper.rb
module TraysHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_form.html.erb
<div class="card border-dark mb-3" style="padding:7px">
<%= form_with(model: customer, local: false) do |form| %>
<li style="list-style: none">
<%= form.label :name, "Nombre" %>
<%= form.text_field :name %>
<li style="list-style: none">
<%= form.label :last_name, "Apellidos" %>
<%= form.text_field :last_name %>
<li style="list-style: none">
<%= form.label :phone, "Telefono" %>
<%= form.text_field :phone %>
<li style="list-style: none">
<%= form.label :adress, "Direccion Entrega" %>
<%= form.text_field :adress,:size=>"20",:height=>"30" %>
<li style="list-style: none">

<%= form.label :comuna, "Comuna" %>
<%= form.collection_select :comuna, @comunas, :to_s, :to_s %>
<li style="list-style: none">

<%= form.label :ident, "Email Transferencia" %>
<%= form.text_field :ident %>
</ul>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions" style="margin-top:20px">
    <%= form.submit "Actualizar Info",class: ["btn", "btn-primary"], style:["padding-left:40px; padding-right:40px"]%>
  </div>
<% end %>
</div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>