config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "users/sign_out", to: "users#logy"
  get 'add_item/:coc_id', to: "roads#add_item", as: 'add_item'
  get 'add_item_last/:coc_id', to: "roads#add_item_last", as: 'add_item_last'
  get 'eliminate_tray/:i_id', to: "roads#eliminate_item", as: 'eliminate_item'
  get 'pay/:order_id', to: "orders#pay", as: 'pay'
  get 'wait/:order_id', to: "orders#wait", as: 'wait'
  get 'admin', to: "orders#admin", as: 'admin'
  get 'search', to: "orders#pannel"
  get 'ready/:id', to: "orders#ready", as: 'ready'
  get 'disp/:id', to: "orders#disp", as: 'disp'
  get 'elim/:id', to: "orders#elim", as: 'elim'
  get 'elim2/:id', to:"orders#elim2", as: 'elim2'
  get 'pending', to: "orders#pending", as: 'pending'
  resources :users
  resources :customers do
    resources :orders
  end
  resources :trees do
    resources :roads
  end
  resources :trees
end

#sample@sample.com123456

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :roads
  

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show]

  # GET /orders
  # GET /orders.json
  def index
    @order = Order.where(id:cookies[:current_order_idd]).first
    @order_id = @order.id
    @trays = Road.where(order_id:cookies[:current_order_idd])
    @total = 0
    @trays.each do |tray|
      begin
        @total += tray.tree.price.split('$')[1].to_i
      rescue => exception
        total += 1
      end
    end
  end
def disp
  ig = params[:id]
  o = Order.where(id:ig).first
  o.disp = true
  e = Order.new
  e.customer_id = o.customer_id
  e.finished = o.finished
  e.personal = o.personal
  e.disp = o.disp
  e.finished = false
  e.almost = false
  e.copy = true
  e.total = o.roads.count
  e.ident = o.id
  e.content= o.content
  e.save!
  o.disp = true
  o.almost = false
  o.finished = false
  o.save!
  respond_to do |format|
    format.html { redirect_to search_path}
  end
end
def elim
  if current_user.admin
    t = Order.where(id:params[:id]).first
    t.disp = false
    t.almost = false
    t.finished = false
    t.ident = 0
    t.save!
    respond_to do |format|
      format.html { redirect_to search_path}
    end
  end
end
def pending
  if (Customer.where(id:cookies[:customer_idd]).first.ident== nil || Customer.where(id:cookies[:customer_idd]).first.ident== "")
    flash.now[:notice] = 'Ingesar un Email'
    respond_to do |format|
      format.html { redirect_to pay_path(Order.where(id:cookies[:current_order_idd]).first.id)}
    end
  elsif (Customer.where(id:cookies[:customer_idd]).first.adress== nil || Customer.where(id:cookies[:customer_idd]).first.adress== "")
    flash.now[:notice] = 'Ingesar una direccion de entrega'
    respond_to do |format|
      format.html { redirect_to pay_path(Order.where(id:cookies[:current_order_idd]).first.id)}
      
    end
  end
end
def elim2
  if current_user.admin
    t = Order.where(id:params[:id]).first
    t.disp = false
    t.almost = false
    t.finished = false
    t.copy = false
    t.save!
    t.roads.each do |e|
      e.destroy!
    end
    t.destroy!
    respond_to do |format|
      format.html { redirect_to search_path}
    end
  end
end
def wait
  o = Order.where(id:cookies[:current_order_idd]).first
  e = Order.new
  cont = ""
  o.roads.each do |tray|
    cont += tray.tree.id.to_s
    cont += ";"
  end
  e.customer_id = o.customer_id
  e.finished = o.finished
  e.personal = o.personal
  e.disp = o.disp
  e.finished = false
  e.almost = true
  e.copy = false
  e.content = cont
  e.total = o.roads.count
  e.ident = o.id
  e.save!
  o.save!
  @user = Customer.where(id:cookies[:customer_idd]).first
  UserMailer.with(user: @user).welcome_email.deliver_now
end
def admin
end
def pannel
  @venta_id_1 = 0
  @venta_id_2 = 0
  @venta_id_3 = 0
  @venta_id_4 = 0
  @venta_id_5 = 0
  @venta_id_6 = 0
  Order.where(copy:true).each do |order|
    begin
     order.content.split(";").each do |idod|
      idd=idod.to_s
      if idd=="1"
        @venta_id_1 +=1
      end
      if idd=="2"
        @venta_id_2 +=1
      end
      if idd=="3"
        @venta_id_3 +=1
      end
      if idd=="4"
        @venta_id_4 +=1
      end
      if idd=="5"
        @venta_id_5 +=1
      end
      if idd=="6"
        @venta_id_6 +=1
      end
     end
    rescue => exception
    
    end
  end
  @items_saled = 0
  Order.where(copy:true).each do |order|
    begin
      order.content.split(";").each do |element|
        @items_saled += 1
      end
      @items_saled += -1
    rescue => exception
    end
  end
end
def ready
  if current_user.admin
    ig = params[:id]
    o = Order.where(id:ig).first
    o.finished = true
    o.almost = true
    o.disp = false
    o.save!
    begin
      @user = Customer.where(id:o.customer_id).first
      UserMailer.with(user: @user).ready_email.deliver_now
      respond_to do |format|
          format.html { redirect_to search_path}
      end
    rescue => exception
    end
  end
end
def pay
  @comunas = []
  @comunas.push("Vitacura")
  @comunas.push("Las Condes")
  @comunas.push("Lo Barnechea")
  @comunas.push("Providencia")
  @order = Order.where(id:cookies[:current_order_idd]).first
  @order_id = @order.id
  @trays = Road.where(order_id:cookies[:current_order_idd])
  @total = 0
  @trees_ids = []
  @trays.each do |tray|
    @trees_ids.push(tray.tree.id)
    begin
      @total += tray.tree.price.split('$')[1].to_i
    rescue => exception
      total += 1
    end
  end
  @trees_ids = @trees_ids.uniq
  if (Customer.where(id:cookies[:customer_idd]).first.ident== nil || Customer.where(id:cookies[:customer_idd]).first.ident== "")
    flash.now[:notice] = 'Ingesar un Email'
  
  end
  if (Customer.where(id:cookies[:customer_idd]).first.adress== nil || Customer.where(id:cookies[:customer_idd]).first.adress== "")
    flash.now[:notice] = 'Ingesar una direccion de entrega'
  
  end

end
  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end
  def add_item

  end
  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.fetch(:order, {}).permit(:finished, :discount,:customer_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/admin.html.erb
<form action="/search">
<input name="q" type="text" placeholder="Secret admin psw">
<button type="submit">Controll pannel</button>

app/views/orders/index.html.erb
<div style="marign-left:310px">
<div class="row" style="margin-top:20px">
  <div class="col-3" >
  <%cookies_to_show = Tree.first(2)%>
      <div class="card-group" style="margin-left:10px">
      <%cookies_to_show.each do |cookie|%>
        <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%=cookie.name%></h5>
              <%=image_tag("cookie.jpg",:size => "170x170") %>
              <p class="card-text"> </p>
              <%= link_to "Add",add_item_last_path(2),class: ["btn", "btn-primary"] %>
            </div>
          </div>
            <%end%>
        </div>
      </div>
    <div class="col-9">
    <div style="margin-right:25px">
    <table class="table table-hover" style="background-color: #f2f2f2;">
    <tr>
    <th>#</th>
    <th>Galleta</th>
    <th>Precio</th>
    <th>Eliminar</th>
    </tr>
    <% cont = 1%>
      <% @trays.each do |tray|%>
        <tr>
        <td><%= cont%></td><%cont+=1%>
        <td><%=tray.tree.name%></td>
        <td><%= tray.tree.price%></td>
        <td><%= link_to "X", eliminate_item_path(tray.id),class: ["btn", "btn-danger"]%></td>
        </tr>
      <%end%>
      <tr>
        <td></td>
        <td></td>
        <td>TOTAL</td>
        <td><%= @total%></td>
      </tr>
      </table>
          <%= link_to "Pagar", pay_path(@order_id),class: ["btn", "btn-primary"]%>

      </div>
</div>
<div class="row" style="margin-top:40px">
<div class="col-3" >
      </div> 
    <div class="col-9">
    </div>
</div>
</div>

app/views/orders/pannel.html.erb
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <%=link_to "Log in", new_user_session_path%>

<% order = Order.where(id:cookies[:current_order_idd]).first%>
<div class="row" style="margin-top:20px">
  <div class="col-6" >
  <h3>Por Confirmar</h3>
  <table class="table table-bordered">
  <tr>
    <th>#</th>
    <th>Cuando se hizo</th>    
    <th>Quien la hizo</th>
     <th>Total $$</th>
    <th>Confirmar Pedido</th>
  </tr>
    <%cont = 1%>
  <%Order.where(almost:true).where(finished:false).each do |order|%>
  <tr>
    <td><%=cont%></td><%cont += 1%>
    <td><%=order.created_at.to_date%></td>    
    <td><%=order.customer.name%></td>
    <%tott = 0%>
    <%order.content.split(";").each do |de|%>
    <%olg = Tree.where(id:de).first.price.split("$")[1]%>
    <% tott += olg.to_i%>
    <% end%>
    <td><%= tott%></td>
    <td><%= link_to "Aprobar", ready_path(order.id),method: :get,class: ["btn", "btn-success"] %></td>
        
    </tr>
  <% end %>
  </table>
  </div>
    <div class="col-6" >
      <h3>Confirmados Por Entregar</h3>
  <table class="table table-bordered">
  <tr>
    <th>#</th>
    <th>Quien la hizo</th>    
    <th>Comuna</th>
    <th>Donde?</th>
    <th>Despachar Pedido</th>
    <th>Eliminar</th>
  </tr>
    <%cont = 1%>
  <%Order.where(finished:true).each do |order|%>
  <tr>
    <td><%=cont%></td><%cont += 1%>
    <td><%=order.customer.name%></td>
        <td><%=order.customer.comuna%></td>    
    <td><%=order.customer.adress%></td>
    <td><%= link_to "Despachar", disp_path(order.id),method: :post,class: ["btn", "btn-primary"] %></td>
    <td><%= link_to "Eliminar", elim_path(order.id),class: ["btn", "btn-danger"] %></td>
    </tr>
  <% end %>
  </table>
  </div>
</div>
<div class="row" style="margin-top:20px">
<div class="col-6" >
      <h3>Entregados</h3>
  <table class="table table-bordered">
  <tr>
    <th>#</th>
    <th>Cuando se hizo</th>    
    <th>Quien la hizo</th>
    <th>Eliminar Registro</th>
  </tr>
    <%cont = 1%>
  <%Order.where(copy:true).each do |order|%>
  <tr>
    <td><%=cont%></td><%cont += 1%>
    <td><%=order.created_at.to_date%></td>    
    <td><%=order.customer.name%></td>
    <td><%= link_to "Eliminar", elim2_path(order.id),class: ["btn", "btn-danger"] %></td>
    </tr>
  <% end %>
  </table>
  </div>
  <div class="col-6" >

<ul class="list-group">
  <li class="list-group-item">Estadisticas</li>
  <li class="list-group-item list-group-item-primary">Items Vendidos: <%= @items_saled%></li>
  <li class="list-group-item list-group-item-secondary">Computadores registrados en la base de datos: <%=Customer.count %></li>
  <li class="list-group-item list-group-item-success">Visitas diarias <%= Order.where("updated_at BETWEEN ? AND ?", Time.zone.now.beginning_of_day, Time.zone.now.end_of_day).where(copy:false).count%></li>
  <li class="list-group-item list-group-item-danger">Visitas semanales <%= Order.where("updated_at BETWEEN ? AND ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).where(copy:false).count%></li>
  <li class="list-group-item list-group-item-warning">Visitas mensuales <%= Order.where("updated_at BETWEEN ? AND ?", Time.zone.now.beginning_of_month, Time.zone.now.end_of_month).where(copy:false).count%></li>
  <li class="list-group-item list-group-item-info">Carritos de compra que nunca depositaron <%= Order.where(copy:false).where(disp:false).where(almost:false).where(finished:false).count%></li>
  <li class="list-group-item list-group-item-light">Venta item 1: <%= @venta_id_1%></li>
    <li class="list-group-item list-group-item-light">Venta item 2: <%= @venta_id_2%></li>
  <li class="list-group-item list-group-item-light">Venta item 3: <%= @venta_id_3%></li>
  <li class="list-group-item list-group-item-light">Venta item 4: <%= @venta_id_4%></li>
  <li class="list-group-item list-group-item-light">Venta item 5: <%= @venta_id_5%></li>
  <li class="list-group-item list-group-item-light">Venta item 6: <%= @venta_id_6%></li>
</ul>
</div>
</div>

app/views/orders/pay.html.erb
<div style="background-color:#e5e5e5">
<div style="marign-left:310px">
<div class="row" >
<div class="col-2" >
</div>
  <div class="col-3" >
  <%customer = Customer.where(id:cookies[:customer_idd]).first%>
<div style="margin-left:20px">
<div class="alert alert-success" id="notice" >
<%= notice %></div>
    <%= render partial: 'customers/form', locals: {customer: customer} %>
    </div>
    <div class="row" style="margin-left:20px">
        <div class="card text-white bg-info mb-3" style="margin-top:20px">
        <div class="card-header">Informacion Pago
        </div>
        <div class="card-body">El pago de los productos se hace con un deposito que, al validarse, es despachado. <br>Sera informado de todos los moviemientos bia email <br> al siguente mail:<h3><%=Customer.where(id:cookies[:customer_idd]).first.ident%></h3></div>
        </div>
</div>
     
 
      </div>
      
    <div class="col-5">

    <table class="table table-bordered">
     <thead>
    <tr>
    <th>Item</th>
    <th>Eliminar?</th>
    <th>Cantidad</th>
    </tr>
     </thead>
       <tbody>

        <%@trees_ids.each do |tray|%>
    <tr>
    <td>    <%= Tree.where(id:tray).first.name%></td>
    <td>    <%= link_to "-1", eliminate_item_path(Road.where(order_id:@order_id).where(tree_id:tray).first.id),class: ["btn", "btn-danger"]%></td>
    <td>   <button type="button" class="btn btn-outline-info">
<%= Road.where(order_id:@order_id).where(tree_id:tray).count%></button></td>
    </tr>
      <%end%>

  </tbody>

</table>

<div class="card border-success mb-3" style="margin-top:20px">

<div class="card-header">
  <h3>Total: $ <%=@total%></h3>

</div>
  <div class="card-body">
  <%= link_to "Continuar", pending_path(),class: ["btn", "btn-success"]%>
    <%= link_to "Cancelar pago", customer_orders_path(cookies[:customer_idd],cookies[:current_order_idd]),class: ["btn", "btn-danger"]%>

  </div>
</div>
  
    </div>
</div>
  <div class="col-2" >
</div>
<div class="row" style="margin-top:40px">
<div class="col-3" >
      </div> 
    <div class="col-9">
    </div>
</div>
</div>
<div class="row" style="background-color:#e5e5e5; height:400px">
</div>

app/views/orders/pending.html.erb
  <div class="row" style="height:350px;background-image: url(<%= image_path 'Banner.jpg' %>)">
    <div class="col-4">
    </div>
    
    <div class="col-8">
    <div class="card" style="width: 39rem; margin-top:20px; margin-bottom:20px">
      <div class="card-body">
        <h5 class="card-title">Informacion Deposito</h5>
<span>Banco:Banco Edwards<br>
Tipo: Cuenta corriente<br>
Cuenta:  8090015109 <br>
  Rut:  19.636.903-1<br>
  Nombre: Sebastian Hirsch<br>
  mail: Ventasrushbakery@gmail.com<br>
  Asunto: Pago mail "<strong><%= Customer.where(id:cookies[:customer_idd]).first.ident%><strong>"<span>
  <%= link_to "Listo!", wait_path(cookies[:current_order_idd]),class: ["btn", "btn-primary"],style: ["margin-left:380px; width:130px"]%>
      </div>
    </div>
    </div>

  </div>
</div>

app/views/orders/wait.html.erb
  
  <div class="row" style="height:270px ;background-image: url(<%= image_path 'Banner.jpg' %>)">
    <div class="col-4">
    </div>
    
    <div class="col-8">
    <div class="card" style="width: 39rem; margin-top:20px; margin-bottom:20px">
      <div class="card-body">
        <h5 class="card-title">Listo pedido ingresado!</h5>
        <p class="card-text">Tu pedido Esta en proceso de confirmacion, te hemos mandado un mail , una vez que se acepte el deposito podras ver el estado de tu pedido en la pagina principal!</p>

        <%= link_to "Pagina principal", root_path,class: ["btn", "btn-primary"]%>
      </div>
    </div>
    </div>

  </div>
</div>